'use strict';
const $=id=>document.getElementById(id), raw=['trq_measured','oat','mgt','pa','ias','np','ng'];
let summary,offset=0,total=0,selected=null,rows=[];
function el(tag,text,cls){const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(cls)n.className=cls;return n;}
const num=(x,d=2)=>x==null?'—':Number(x).toFixed(d), pct=x=>x==null?'—':(100*x).toFixed(2)+'%';
async function api(path,body){const r=await fetch(path,body?{method:'POST',headers:{'Content-Type':'application/json','X-Session-Token':summary.session_token},body:JSON.stringify(body)}:{});const d=await r.json();if(!r.ok)throw Error(d.error||r.statusText);return d;}
function showError(e){$('error').textContent=e.message||String(e);}
async function loadRows(){try{const d=await api('/api/observations?offset='+offset+'&q='+encodeURIComponent($('search').value)+'&filter='+$('filter').value+'&scope='+$('scope').value+'&sort='+$('sort').value);total=d.total;rows=d.rows;$('rows').replaceChildren();for(const r of rows){const tr=el('tr');tr.dataset.id=r.id;const a=el('td',r.id);a.append(el('span',r.engine_id?`${r.engine_id} / ${r.flight_id}`:'Engine unavailable','muted'));const m=el('td',num(r.margin_mean)+' pp');m.append(el('span',`${num(r.margin_low_90)} to ${num(r.margin_high_90)}`,'muted'));const rel=el('td');rel.append(el('span',r.reliability_status.replaceAll('_',' '),'badge '+r.reliability_status));const priority=el('td',r.review_priority);priority.append(el('span',r.latest_disposition||'Not yet reviewed','muted'));tr.append(a,el('td',pct(r.p_faulty)),m,rel,priority);tr.addEventListener('click',()=>detail(r));$('rows').append(tr);}$('page').textContent=total?`${offset+1}–${Math.min(offset+100,total)} of ${total}`:'No observations';$('prev').disabled=offset===0;$('next').disabled=offset+100>=total;}catch(e){showError(e);}}
async function detail(r){selected=r;$('choose').hidden=true;$('details').hidden=false;const box=$('detailcontent');box.replaceChildren();box.append(el('h3',r.id));const dl=el('dl');for(const [key,v] of [['Priority',r.review_priority],['Latest disposition',r.latest_disposition||'Not yet reviewed'],['Latest reviewer',r.latest_reviewer||'—'],['Reviewed at',r.latest_review_at||'—'],['P(fault)',pct(r.p_faulty)],['Fault flag',r.fault_flag==null?'No prediction':r.fault_flag?'Flagged':'Below threshold'],['Reliability',r.reliability_status],['Regime',r.regime],['Joint distance',num(r.joint_distance,4)],['Environment distance',num(r.environment_distance,4)],['Seen training/calibration',r.training_or_calibration_duplicate?'Yes':'No'],['Confirmed fault',r.faulty==null?'Unavailable':r.faulty],['Actual margin',num(r.trq_margin)],...raw.map(c=>[c,num(r[c])])]){dl.append(el('dt',key),el('dd',String(v)));}box.append(dl,el('p',r.priority_reason),el('p',r.latest_review_note||''),el('h3','Review reasons'),el('p',r.review_reason||'No provisional reliability warning. This is not a guarantee of safety.'));$('reviewmessage').textContent='';$('history').replaceChildren();if(r.engine_id){const h=await api('/api/history?engine='+encodeURIComponent(r.engine_id));$('history').append(el('p',h.note));for(const t of h.rows.slice(-10))$('history').append(el('p',`${t.timestamp_utc} · P(fault) ${pct(t.p_faulty)} · margin ${num(t.margin_mean)} pp`));}else $('history').textContent='Engine IDs and timestamps are unavailable; row order is not history.';for(const c of raw)$('measure_'+c).value=r[c]??'';}
function renderMetrics(){const e=summary.evaluation,c=e.metrics?.classification,r=e.metrics?.regression;const box=$('metrics');box.replaceChildren();box.append(el('p',`Labelled: ${e.labelled??0}. Invalid: ${e.invalid??'—'}. Seen feature duplicates: ${e.seen_duplicate_labelled??'—'}. Evaluated: ${e.evaluated_independent_feature_rows??0}.`));box.append(el('p',e.acceptance||e.status||''));if(c){const grid=el('div',undefined,'metricgrid');for(const [label,value] of [['Fault recall',pct(c.recall_faulty)],['Missed faults',c.false_negatives],['False alerts',c.false_positives],['Margin MAE',num(r.mae)+' pp'],['Brier score',num(c.brier,5)],['90% coverage',pct(r.interval_90_coverage)],['Accuracy',pct(c.accuracy)],['90% width',num(r.interval_90_mean_width)+' pp']]){const a=el('article');a.append(el('span',label),el('b',String(value)));grid.append(a);}box.append(grid);}$('slices').replaceChildren();for(const s of e.slices||[]){const tr=el('tr');for(const v of [s.dimension,s.value,s.n,s.false_negatives,s.false_positives,pct(s.recall),num(s.mae),pct(s.coverage_90)])tr.append(el('td',String(v)));$('slices').append(tr);}$('events').textContent=JSON.stringify({flight_events:e.flight_events,lead_time_note:e.lead_time_note},null,2);$('coverage').textContent=JSON.stringify(summary.manifest.baseline.coverage_evidence,null,2);}
async function audit(){const d=await api('/api/reviews');$('auditrows').replaceChildren();for(const r of d.rows){const a=el('article');a.append(el('strong',`${r.observation_id} · ${r.disposition}`),el('p',`${r.reviewer} · ${r.at_utc}`),el('p',r.note));$('auditrows').append(a);}if(!d.rows.length)$('auditrows').append(el('p','No reviews yet.'));}
async function init(){try{summary=await api('/api/summary');const m=summary.manifest;$('mode').textContent=m.mode.toUpperCase();$('baseline').textContent=m.baseline.name;$('hash').textContent='SHA256 '+m.baseline.baseline_sha256;$('context').textContent=m.workflow;$('threshold').textContent=`Frozen fault threshold ${num(m.baseline.threshold,3)} · Reliability policy: provisional`;$('total').textContent=summary.counts.total.toLocaleString();$('review').textContent=summary.counts.open_review.toLocaleString();$('flags').textContent=summary.counts.fault_flags.toLocaleString();$('rejected').textContent=summary.counts.rejected.toLocaleString();$('runtimeinfo').textContent='Runtime preflight passed · scikit-learn '+summary.runtime.installed.sklearn+' · '+(summary.runtime.unrecorded_packages.length?'Legacy manifest: some dependency versions were not recorded.':'All monitored package versions recorded.');for(const c of raw){const label=el('label',c),input=el('input');input.type='number';input.step='any';input.required=true;input.id='measure_'+c;label.append(input);$('measurementfields').append(label);}renderMetrics();await loadRows();}catch(e){showError(e);}}
for(const b of document.querySelectorAll('[data-tab]'))b.addEventListener('click',async()=>{document.querySelectorAll('.tab').forEach(t=>t.hidden=t.id!==b.dataset.tab);document.querySelectorAll('[data-tab]').forEach(x=>x.classList.toggle('active',x===b));if(b.dataset.tab==='audit')try{await audit();}catch(e){showError(e);}});
$('refresh').onclick=()=>{offset=0;loadRows();};$('filter').onchange=()=>{offset=0;loadRows();};$('scope').onchange=()=>{offset=0;loadRows();};$('sort').onchange=()=>{offset=0;loadRows();};$('search').onkeydown=e=>{if(e.key==='Enter'){offset=0;loadRows();}};$('prev').onclick=()=>{offset=Math.max(0,offset-100);loadRows();};$('next').onclick=()=>{offset+=100;loadRows();};$('auditrefresh').onclick=()=>audit().catch(showError);
$('reviewform').onsubmit=async e=>{e.preventDefault();if(!selected)return;try{const r=await api('/api/review',{id:selected.id,reviewer:$('reviewer').value,disposition:$('disposition').value,note:$('note').value});const fresh=await api('/api/observation?id='+encodeURIComponent(selected.id));if(fresh.rows.length)await detail(fresh.rows[0]);await loadRows();const status=await api('/api/summary');$('review').textContent=status.counts.open_review.toLocaleString();$('reviewmessage').textContent=r.status;}catch(err){showError(err);}};
$('predictform').onsubmit=async e=>{e.preventDefault();const observation={id:'manual-'+Date.now()};for(const c of raw)observation[c]=Number($('measure_'+c).value);try{$('predictresult').textContent=JSON.stringify(await api('/api/predict',{observations:[observation]}),null,2);}catch(err){showError(err);}};
init();
